### ISSUE TITLE
First Simple Machine: there's no "type" on output/input components

### ISSUE THREAD

**Issue by VoxTenebris** [satisfactorymodding/Documentation#100]
Hi, the docs' **First Simple Machine** there's a paragraph that states:

> _Set the output component’s `direction` property to output and the `type` to Item. Do the same for the input component, but change its direction property to input._

I searched carefully, but I couldn't find any `type` on output/input components 😕 

https://docs.ficsit.app/satisfactory-modding/latest/Development/BeginnersGuide/SimpleMod/machines/SimpleMachine.html#_create_the_machine

![image](https://user-images.githubusercontent.com/94031037/146632399-7c2f01cc-05f3-4c4a-a823-5c9323d1a4a0.png)

**Comment by budak7273** [comment]
This tutorial hasn't been updated for a bit... I'm guessing it's now `M Connector` to `Conveyor`? Are you able to confirm this?

**Comment by VoxTenebris** [comment]
Sorry, I completely forgot about this issue. Yes, it's `M Connector` now.
