### ISSUE TITLE
Can't build the docs

### ISSUE THREAD

**Issue by ARtemachka** [satisfactorymodding/Documentation#106]
I get the following error while building the docs:

> artemachka@artemachka-VirtualBox:~/Satisfactory/Documentation$ yarn run build
yarn run v1.22.17
$ antora antora-playbook.yml --clean --fetch
[clone] https://github.com/satisfactorymodding/Documentation.git     [####################################################################################################]
[clone] https://github.com/CoderDE/FicsIt-Networks.git               [####################################################################################################]
[clone] https://git.hostxtra.co.uk/publicrefinedrd/refinedrddocs.git [####################################################################################################]
[clone] https://github.com/Feyko/Tweaker.git                         [####################################################################################################]
[clone] https://github.com/porisius/FicsitRemoteMonitoring.git       [####################################################################################################]
[clone] https://github.com/Kyri123/KMods-Docs.git                    [####################################################################################################]
[clone] https://github.com/budak7273/ContentLib_Documentation.git    [####################################################################################################]
**error: Duplicate nav in Development@ficsitremotemonitoring: modules/ROOT/nav.adoc
  1: docs/modules/ROOT/nav.adoc in https://github.com/porisius/FicsitRemoteMonitoring.git (ref: dev)
  2: docs/modules/ROOT/nav.adoc in https://github.com/porisius/FicsitRemoteMonitoring.git (ref: main)**
Add the --stacktrace option to see the cause.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

I guess it is connected to [this commit](https://github.com/satisfactorymodding/Documentation/commit/68eef753f3d3b55b216d112729c26aa0259dae7c). After reverting the commit I was able to successfully build the docs.

**Comment by budak7273** [comment]
@ARtemachka Can you confirm that this is resolved (on the Dev branch?)

**Comment by ARtemachka** [comment]
@budak7273 The issue is gone now, thanks :)
