### ISSUE TITLE
Instructions Needed (Provided) for Getting Started's Create An Item Tutorial

### ISSUE THREAD

**Issue by GreyHak** [satisfactorymodding/Documentation#118]
I would like to recommend changes to the BeginnersGuide/SimpleMod/item.html page.  It is currently redirecting users to Conveyor Rendering, but that page is noted as out of date.  A far better and current link would be Development/Modeling/MainMaterials.html#_factory_baked_mm_factorybaked.  If you want to include the some hand-holding steps, that would probably be useful too.

1. Navigate to Content\FactoryGame\MasterMaterials
2. Right-click on MM_FactoryBaked and select Create Material Instance
3. Drag-drop the new MM_FactoryBaked_Inst into the folder with your mesh, and select Move Here
4. Double-click the new MM_FactoryBaked_Inst
5. Under Global Texture Parameter Values, enable Normal and set it to Tex_Doc-Item_N
6. Enable Albedo and set it to Tex_Doc-Item_AB
7. Enable ReflectionMap and set it to Tex_Doc-Item_MREO
8. Double-click on your item mesh (from Mesh_Doc-Item in the example), and set the Material Slot Element 0 to MM_FactoryBaked_Inst.

Great tutorial!  Thank you!

**Comment by budak7273** [comment]
I am pretty sure that #124 has now corrected this, but please let us know if there are still any issues. Thanks!
