### ISSUE TITLE
VS2019

### ISSUE THREAD

**Issue by Zombie-Gnomes** [satisfactorymodding/Documentation#131]
Following the instructions with VS2022 doesn't work as the directory 
C:\Program Files\Unreal Engine - CSS\Engine\Extras\UnrealVS\ 

only has:
VS2015
VS2017
VS2019

These are not compatible it seems with VS 2022.

Either a new plugin needs to be found or the user needs to be directed to install to VS2019 instead of VS2022 earlier in the tutorial.
VS2019 downloads exists here.
https://my.visualstudio.com/Downloads?q=Visual%20Studio%202019

I'm not sure if another plugin can be located so I reported an issue before editing the page as I didn't find anything when searching through the internet.

**Comment by Zombie-Gnomes** [comment]
seems for UE4 we should direct the user to use VS2019 instead of VS2022

https://www.reddit.com/r/unrealengine/comments/uh19bi/visual_studio_2022_doesnt_detect_unrealvs_2019/

**Comment by budak7273** [comment]
Since the VS plugin is not super useful, we decided to remove the mention of installing the plugin from the docs in 7237982
