### ISSUE TITLE
Cannot find "M Interact Object"

### ISSUE THREAD

**Issue by hahoyer** [satisfactorymodding/Documentation#144]
On page "SimpleInteraction" there is stated
"The FGInteractWidget has the M Interact Object variable which represents the ...".

I created a blueprint class from FGInteractWidget besides buildable stuff. 
But it does not show the "M Interact Object"-variable when I open it in the designer.
![image](https://user-images.githubusercontent.com/144392/194957351-381a7b08-ebdb-4b5f-8900-63348d598c59.png)

**Comment by budak7273** [comment]
Sorry it took so long to get around to clarifying this - we have been planning to replace this docs page with a better introduction to custom buildables.

See ff59df5
