### ISSUE TITLE
"Welcome to the Community" guide

### ISSUE THREAD

**Issue by budak7273** [satisfactorymodding/Documentation#180]
Currently this info is spread across a bunch of discord bot commands and outdated ficsit.app guides that can't be edited by the community.

It should cover:
- Navigating SMR
- How to download SMM
- Walk through using SMM to install a mod
- SMM and mods are safe as long as you download them from ficsit.app, even though the computer may warn about running it, we just don't pay for a certificate (see the >virus Fred command)

it should replace these bot commands:
`>welcome`
`>newbie`
`>virus`

**Comment by budak7273** [comment]
Some of this info is now on the FAQ page

**Comment by porisius** [comment]
Downloading SMM
https://docs.ficsit.app/satisfactory-modding/latest/faq.html#_are_satisfactory_mods_safe

Install Mods
https://docs.ficsit.app/satisfactory-modding/latest/faq.html#_installing_mods

>virus
https://docs.ficsit.app/satisfactory-modding/latest/faq.html#_are_satisfactory_mods_safe

**Comment by xXdrewbaccaXx** [comment]
@porisius Your downloading SMM link is the same as the one for >virus.

I assume this is what you meant to link? (https://docs.ficsit.app/satisfactory-modding/latest/faq.html#_how_do_i_install_mods)

**Comment by porisius** [comment]
Probably a case of accidental copy/pasta, thanks

**Comment by budak7273** [comment]
That FAQ item should probably be updated anyways - it talks about how to install the mod manager, but not how to actually interact with the mod manager (or website). This guide has that info, maybe we should try to move that in: https://ficsit.app/guide/NG4DD9UhWjMUK


Also we should add the winget install directions (it might be `winget install SatisfactoryModManager`, someone in the community set it up, we don't manage it afaik)

**Comment by xXdrewbaccaXx** [comment]
Might be a good idea to make new images that don't feature the More Milestones mod, what with it not existing anymore...and the errr "controversy".

While we're on the topic of moving things around.
Kyrium's guide on creating new swatches(https://ficsit.app/guide/8RQqqjxcaAGpcb) would probably be better purposed as a new .adoc  under Community Resources on docs.ficsit.app instead.

**Comment by budak7273** [comment]
I added some info for actually interacting with the mod manager to the faq in 57d6bf8

**Comment by budak7273** [comment]
Implemented and commands changed
