### ISSUE TITLE
Replication docs page

### ISSUE THREAD

**Issue by budak7273** [satisfactorymodding/Documentation#183]
Add docs note about multiplayer replication SML RCOs multicast not working because they're on controller -> not on every side, instead need to use a replicated subsystem or similar for this

**Comment by mrhid6** [comment]
Not confirmed but could you use RPC functions Server and NetMulticast for dedicated servers as RCOs relies on player controller

**Comment by budak7273** [comment]
Update the existing multiplayer page with the new example(s) for registering RCOs since the old one uses hooks https://discord.com/channels/555424930502541343/562722670974599227/1118628268606750720

**Comment by budak7273** [comment]
Progress in b3b5d9a
