### ISSUE TITLE
Contributing guidelines

### ISSUE THREAD

**Issue by Superd22** [satisfactorymodding/Documentation#20]
Hey guys, Thanks for the great work.

I'm currently tickering with SML for the first time, working on implementing a new Equipement in game.

The docs are currently very lackluster around that topic, are PR welcome ? If so, should we target develop or master ?

**Comment by Panakotta00** [comment]
Well...
If you want to make a PR, you should target the Dev branch...
But i dont think that a PR for Equip should be done right now, cause we excpect changes to it cause for us modders... it is heavily limited in what we can do ^^

**Comment by Superd22** [comment]
Yeah, i'd assume most undocumented stuff is heavy WIP.

But then again, even just listing those limitations and expected changes might save a few people (myself included) some time.
