### ISSUE TITLE
The discord link is no longer valid

### ISSUE THREAD

**Issue by mactron254** [satisfactorymodding/Documentation#232]
I have tried to join the discord server, on the web and on github and all the links indicate that they are expired

**Comment by MinoDab492** [comment]
Which link did you try to use. When I go through the link on the main page it seems to work.

**Comment by budak7273** [comment]
Please send a screenshot of the page containing the link you clicked and the URL of the page you were on

**Comment by budak7273** [comment]
@mactron254 any updates?

**Comment by MinoDab492** [comment]
@budak7273 Should the issue should be closed? It's inactive, and we haven't been able to recreate/find the issue.
