### ISSUE TITLE
Sample Image (SoonTM) not supported in UE5

### ISSUE THREAD

**Issue by gwilku** [satisfactorymodding/Documentation#310]
The sample image on the Recipe vs Schematic page in the [Assign Schematic Properties](https://docs.ficsit.app/satisfactory-modding/latest/Development/BeginnersGuide/SimpleMod/recipe.html#_assign_schematic_properties) chapter is not supported by UE5.

The PNG import generates either: no payload & texture has no width errors, or a log entry:

> LogCore: PNG has complex alpha channel, will not fill RGB in transparent background

**Comment by budak7273** [comment]
Fixed in 5b2e72b9981d7ce8fc1b554ced38fee125068af3 , it has to do with cloudflare optimizations turning them into WEBPs instead
