### ISSUE TITLE
Add information on how to make SML working on Linux

### ISSUE THREAD

**Issue by asdkant** [satisfactorymodding/Documentation#34]
After a bit of searching and asking in the Discord channel I figured out that what works (even if it's not all the functionality) is to:
* do the manual installation
* set the steam launch option for satisfactory to `WINEDLLOVERRIDES="msdia140.dll,xinput1_3.dll=n,b" %command%` (or the equivalent with lutrix/epic/whatever)

this is not terribly complicated for someone that is already doing the manual installation, so it'd be useful to have it mentioned there. Some things that could be mentioned:
* mentioning that you're supposed to set an environment variable (so people who don't understand know what to google, and people who do get the idea)
* the wine wiki entry on the [WINEDLLOVERRIDES](https://wiki.winehq.org/Wine_User%27s_Guide#WINEDLLOVERRIDES.3DDLL_Overrides) environment variable, to give context.

If you point which branch it should go to I can make a pull request with these changes.

**Comment by budak7273** [comment]
It looks like some more details were added on this back in #31, but if you'd like to add more, the target branch should be `Dev`.
