### ISSUE TITLE
Misleading information on the use of Notepad in Windows 11.

### ISSUE THREAD

**Issue by NightFire1980** [satisfactorymodding/Documentation#351]
Your documentation suggests that you are unable to open the CustomVersions.json in Notepad due to the UTF16-LE format, which is factually incorrect.

![Image](https://github.com/user-attachments/assets/fd81fb5d-9e5b-431e-b4c6-0cc908123a36)

As you can see it is easily possible to open the file in notepad, and as someone who has used notepad for 30 years or so, I have never known a version  where you cannot specify the encoding when loading a file.

**Comment by budak7273** [comment]
> If you are using Windows 10,
Windows Notepad can successfully load the `CustomVersions.json` file
and you can copy its contents to your clipboard normally.
If you are using Windows 11,
you will need to use another text editor such as https://notepad-plus-plus.org/[Notepad++]. 
Windows 11's Notepad incorrectly loads the file with UTF-8 encoding
and FModel will tell you that you broke the .json if you copy the contents over.

I'm on Win10, so I can't test this, but I assume this failure of the autodetect feature was fixed some time in the past 11 months (last time that line was changed). I'll update the docs to mention ensuring it is opened with the correct encoding,

**Comment by budak7273** [comment]
@NightFire1980 fixed in 97e6dad97d2ea5ec5875e2e6876951a1d0d31bda, please reopen this issue if you have a different suggested wording
